### ISSUE TITLE
`rife-ncnn-vulkan` not using GPU (external issue)

### ISSUE THREAD

**Issue by 15704080** [neggles/animatediff-cli#20]
<img width="383" alt="1691819339439" src="https://github.com/neggles/animatediff-cli/assets/128477008/a4ab8b38-9c33-4477-b742-f5394ae3eb60">

**Comment by 15704080** [comment]
<img width="356" alt="1691819397977" src="https://github.com/neggles/animatediff-cli/assets/128477008/829fd0c0-3b5a-4f87-b886-4aa866ec8c67">

**Comment by neggles** [comment]
Hm. Not sure what's going on there, but I don't control the `rife-ncnn-vulkan` software; I've made some headway in reimplementing the original rife4.6 model code myself, so that this wouldn't be dependent on that (and so I could throw in ESRGAN upscaling at the same time) but most of the known-good reference code I can find is in C++, is a VaporSynth plugin, or both, and I'm not a fan of C++/VS so I've not had a great deal of luck with that.

I suggest trying to run the `rife-ncnn-vulkan` executable yourself, maybe in verbose mode, to see what errors it throws; it's probably a driver/CUDA issue, but it's not one I can debug, really :(
