### ISSUE TITLE
[Feature Request] Ability to change samplers/schedulers

### ISSUE THREAD

**Issue by eldragon0** [neggles/animatediff-cli#4]
This works in the main branch: 
![image](https://github.com/neggles/animatediff-cli/assets/50936701/69f23765-107c-49a1-a73d-6afeccff948a)

Is the error I get on this branch: 
![image](https://github.com/neggles/animatediff-cli/assets/50936701/aad3cb9e-624d-422c-9610-f9b62d039ab0)

**Comment by eldragon0** [comment]
Attempting to set the sampler in the .json you run when you generate works with the main branch but using that same argument with this branch just breaks it.

**Comment by neggles** [comment]
Not entirely sure what branch (do you mean fork?) you're referring to, and as far as I can tell, the original repo just forces you into using DDIM? 🤷‍♀️

That said, have just pushed the ability to set sampler in the prompt JSON file. Because of how the pipeline loading etc. works, it's *not* a list of samplers; you'll have to use the same one for every generation in a single config file.

List of available options is here:

https://github.com/neggles/animatediff-cli/blob/fdfc31975e09dfa7508c6a848dc88c9d72e5ae5d/src/animatediff/schedulers.py#L18-L29

I haven't tested anything other than `k_dpmpp` and `ddim` and make no promises about whether UniPC will work, but I guess it should? check the example prompt configs to see how to specify it.
