### ISSUE TITLE
RIFE questions

### ISSUE THREAD

**Issue by chrish-slingshot** [neggles/animatediff-cli#5]
Is there an extra command line option or something to kick rife off? I've installed as per the instructions but it doesn't seem to be doing anything. Also how to you specify movie output instead of gif?

**Comment by chrish-slingshot** [comment]
One more question - what denoising strength is it using to generate the images? I'm trying to reproduce the initial image using A1111 with the same seed/sampler/steps but no luck so far. Is this even a thing that can be done or does the diff process not work like that?

**Comment by neggles** [comment]
> Is there an extra command line option or something to kick rife off? I've installed as per the instructions but it doesn't seem to be doing anything. Also how to you specify movie output instead of gif?

Apologies for the slow reply 😅 RIFE is a separate subcommand - `animatediff rife interpolate --help` will print details. Generally it's something like;

```
animatediff rife interpolate -z -x -F 50 -M 3 ./00-13163998037304110560
```
with the path at the end pointing to one of the folders full of output frames from a generation.

> One more question - what denoising strength is it using to generate the images? I'm trying to reproduce the initial image using A1111 with the same seed/sampler/steps but no luck so far. Is this even a thing that can be done or does the diff process not work like that?

It's text-to-image, so technically a denoising strength of 1.0, but it's not really a meaningful/configurable thing. As for duplicating outputs, this uses the HuggingFace implementation of the SD pipelines rather than the AUTOMATIC1111 webui implementation and (as far as I know) there's no way to make HF pipelines output exactly the same images as the auto webui 😢 

On top of that, the temporal unet/motion module alters the generation outputs (since that's how it works), so even if you *did* hack up the Unet/sampler implementations to make them identical, the outputs would never be exactly the same. Just the nature of the thing, really.
